services:
  roblox:
    build:
      context: .
    container_name: roblox-docker
    ports:
      - "6080:6080"
    volumes:
      - ./config/sober:/home/roblox/.var/app/org.vinegarhq.Sober
    environment:
      DISPLAY: ":0"
      XDG_RUNTIME_DIR: "/run/user/1000"
      ROBLOX_WIDTH: "1280"
      ROBLOX_HEIGHT: "720"
      LIBGL_ALWAYS_SOFTWARE: "1"
      GALLIUM_DRIVER: "llvmpipe"
      MESA_GL_VERSION_OVERRIDE: "4.6"
      MESA_GLES_VERSION_OVERRIDE: "3.2"
    mem_limit: 2g
    cpus: 2.0
    shm_size: 512m
    restart: unless-stopped
